/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDonationRouter } from "./IDonationRouter";
export type { IYieldStrategy } from "./IYieldStrategy";
