/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  DonationRouter,
  DonationRouterInterface,
} from "../../../contracts/routers/DonationRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "YieldDonated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "donate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610332806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063386bc05a14610030575b600080fd5b61004361003e3660046102c0565b610045565b005b6001600160a01b0383166100ab5760405162461bcd60e51b815260206004820152602260248201527f446f6e6174696f6e526f757465723a207a65726f206173736574206164647265604482015261737360f01b60648201526084015b60405180910390fd5b6001600160a01b0382166101125760405162461bcd60e51b815260206004820152602860248201527f446f6e6174696f6e526f757465723a207a65726f2062656e6566696369617279604482015267206164647265737360c01b60648201526084016100a2565b600081116101625760405162461bcd60e51b815260206004820152601b60248201527f446f6e6174696f6e526f757465723a207a65726f20616d6f756e74000000000060448201526064016100a2565b6101776001600160a01b0384163384846101d3565b336001600160a01b0316826001600160a01b0316846001600160a01b03167f9fca07d716640b54ebcf28c3f29b511153f642fa08bb891c6b24d4c1467f83ef846040516101c691815260200190565b60405180910390a4505050565b604080516001600160a01b0385811660248301528416604482015260648082018490528251808303909101815260849091019091526020810180516001600160e01b03166323b872dd60e01b17905261022d908590610233565b50505050565b600080602060008451602086016000885af180610256576040513d6000823e3d81fd5b50506000513d9150811561026e57806001141561027b565b6001600160a01b0384163b155b1561022d57604051635274afe760e01b81526001600160a01b03851660048201526024016100a2565b80356001600160a01b03811681146102bb57600080fd5b919050565b6000806000606084860312156102d557600080fd5b6102de846102a4565b92506102ec602085016102a4565b915060408401359050925092509256fea264697066735822122066ae691d2ece225fb378ce0c25996548495ddaa7a370c878267166aada5d69d964736f6c63430008140033";

type DonationRouterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DonationRouterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DonationRouter__factory extends ContractFactory {
  constructor(...args: DonationRouterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DonationRouter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DonationRouter__factory {
    return super.connect(runner) as DonationRouter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DonationRouterInterface {
    return new Interface(_abi) as DonationRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DonationRouter {
    return new Contract(address, _abi, runner) as unknown as DonationRouter;
  }
}
