/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDonationRouter,
  IDonationRouterInterface,
} from "../../../contracts/interfaces/IDonationRouter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "YieldDonated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "donate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDonationRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IDonationRouterInterface {
    return new Interface(_abi) as IDonationRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDonationRouter {
    return new Contract(address, _abi, runner) as unknown as IDonationRouter;
  }
}
