/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IYieldStrategy,
  IYieldStrategyInterface,
} from "../../../contracts/interfaces/IYieldStrategy";

const _abi = [
  {
    inputs: [],
    name: "asset",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "divest",
    outputs: [
      {
        internalType: "uint256",
        name: "actuallyDivested",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "harvest",
    outputs: [
      {
        internalType: "uint256",
        name: "yieldAmt",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "invest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalAssets",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IYieldStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): IYieldStrategyInterface {
    return new Interface(_abi) as IYieldStrategyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IYieldStrategy {
    return new Contract(address, _abi, runner) as unknown as IYieldStrategy;
  }
}
